# Generated by Django 5.2 on 2025-04-25 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_app', '0002_user_id_alter_score_user_alter_user_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='score',
            name='score',
        ),
        migrations.AddField(
            model_name='score',
            name='current_score',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='score',
            name='high_score',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
