# Generated by Django 5.2 on 2025-04-25 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_app', '0004_rename_current_score_score_last_game_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='score',
            name='high_score',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='score',
            name='last_game_score',
            field=models.IntegerField(),
        ),
    ]
